<a href="https://colab.research.google.com/github/carolvieirav/Estatistica_Python/blob/main/Estat%C3%ADstica-Descritiva/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numpy Arrays

## Criando uma numpy array de uma lista

*   Item da lista
*   Item da lista



In [ ]:
a = [1,3,5,10]
a

[1, 3, 5, 10]

In [ ]:
b = np.array(a)

In [ ]:
b

array([ 1,  3,  5, 10])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
a * 3

[1, 3, 5, 10, 1, 3, 5, 10, 1, 3, 5, 10]

In [ ]:
b * 3

array([ 3,  9, 15, 30])

In [ ]:
a.append

<function list.append(object, /)>

In [ ]:
b.max()

10

In [ ]:
b.mean()

4.75

In [ ]:
b.argmax()

3

In [ ]:
b.shape

(4,)

* 1-D array

In [ ]:
np.random.randint(0, 100)

48

In [ ]:
np.random.randint(0, 10, size=4)

array([7, 3, 0, 8])

In [ ]:
np.random.randint(0, 10, size=4).shape

(4,)

In [ ]:
np.random.random(size=4)

array([0.24211732, 0.53986733, 0.30087105, 0.98647668])

* 2-D array: **row, column**

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
a[0][-1]

3

In [ ]:
# from a list of lists
b = np.array([[1,2,3],[4,5,6]])

In [ ]:
b[0][-1]

3

In [ ]:
a[0, -1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
b[0,2]

3

In [ ]:
b[1,1]

5

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
b.size

6

In [ ]:
np.random.random(size=(7,4))

array([[0.0475806 , 0.21899082, 0.41925996, 0.36390053],
       [0.50259474, 0.5681986 , 0.22754648, 0.113178  ],
       [0.89566067, 0.74933728, 0.61098718, 0.19204804],
       [0.75433981, 0.54921164, 0.99789319, 0.56975261],
       [0.50752234, 0.11741873, 0.37805641, 0.93283942],
       [0.37554576, 0.81213963, 0.12742458, 0.28006802],
       [0.99787026, 0.46924011, 0.42188027, 0.52640382]])

* 3-D array

In [ ]:
# from a list of list of lists
a = np.array([[[1,2,3],[4,5,6],[7,8,9]],
          [[10,11,12],[13,14,15],[16,17,18]]])

In [ ]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0][1]

array([4, 5, 6])

In [ ]:
a[0][1][2]

6

In [ ]:
a[0,1,2]

6

In [ ]:
a.shape

(2, 3, 3)

In [ ]:
b = np.random.random(size=(4,2,3))

In [ ]:
b

array([[[0.46728726, 0.50970004, 0.13084185],
        [0.69384902, 0.53166858, 0.69192876]],

       [[0.73669708, 0.03205114, 0.56939669],
        [0.27739405, 0.0301216 , 0.66152328]],

       [[0.60015258, 0.68929225, 0.77441248],
        [0.13004818, 0.68008976, 0.40445816]],

       [[0.96742344, 0.41989347, 0.64056641],
        [0.53869263, 0.49841793, 0.86390891]]])

## Partições

In [ ]:
a = np.random.randint(0, 10, size=(4,3))

In [ ]:
my_list = [1,2,4,7,8,10,4,6]

In [ ]:
my_list

[1, 2, 4, 7, 8, 10, 4, 6]

In [ ]:
len(my_list)

8

In [ ]:
my_list[4:]

[8, 10, 4, 6]

In [ ]:
my_list[:3]

[1, 2, 4]

In [ ]:
my_list[:]

[1, 2, 4, 7, 8, 10, 4, 6]

In [ ]:
a

array([[4, 0, 8],
       [8, 2, 3],
       [8, 5, 7],
       [4, 1, 4]])

In [ ]:
# a[row, column]

a[3,2]

4

In [ ]:
a[2:, :]

array([[8, 5, 7],
       [4, 1, 4]])

In [ ]:
a[:, 2]

array([8, 3, 7, 4])

## Outros médotos

In [ ]:
np.zeros(shape=(3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.empty(shape=(3,3) )

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.58095440e-321],
       [1.15706964e-306, 2.33419537e-312, 3.91792476e-317]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
range(10)

range(0, 10)

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
range(0,5,0.5)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
np.dot(np.arange(1,10, 0.5) , np.arange(1,10, 0.5) )

617.25

# Acessando elementos

In [ ]:
array_1d = np.random.random(10)

In [ ]:
array_1d

array([0.14262889, 0.51181858, 0.03821853, 0.05604645, 0.62005312,
       0.85978202, 0.29934158, 0.35627982, 0.38025847, 0.49346816])

In [ ]:
array_2d = np.random.random((5,3))

In [ ]:
array_2d

array([[0.28054149, 0.33433262, 0.79731926],
       [0.81831155, 0.24264351, 0.60602659],
       [0.17313883, 0.31408395, 0.04589798],
       [0.50139267, 0.91388757, 0.53377035],
       [0.49812968, 0.94692612, 0.82961969]])

## For 2-D arrays, there are two ways of doing it.

In [ ]:
array_2d[0]

array([0.20656859, 0.88737349, 0.16138217])

In [ ]:
array_2d[4,2]

0.6293898555326345

In [ ]:
array_2d[4][2]

0.6293898555326345

In [ ]:
array_3d = np.random.random((5,3,4))

In [ ]:
array_3d

array([[[0.40875755, 0.7582361 , 0.22791318, 0.23127454],
        [0.42465146, 0.77629681, 0.99403948, 0.77769779],
        [0.99879582, 0.03099149, 0.81860559, 0.51580583]],

       [[0.57146813, 0.04722416, 0.45294555, 0.18905779],
        [0.63467783, 0.51332971, 0.98199648, 0.34920958],
        [0.75428446, 0.94564528, 0.13366868, 0.8885225 ]],

       [[0.41907688, 0.60010907, 0.06229187, 0.73755725],
        [0.97558476, 0.86335351, 0.58920349, 0.26069347],
        [0.34961859, 0.11745149, 0.25247048, 0.43084913]],

       [[0.79682043, 0.71687694, 0.92731844, 0.23062681],
        [0.54101743, 0.32748859, 0.45288333, 0.64504692],
        [0.85784955, 0.90623177, 0.90981794, 0.89950035]],

       [[0.71955617, 0.96275613, 0.59233063, 0.43989872],
        [0.7639781 , 0.7059774 , 0.1005343 , 0.87468855],
        [0.23484859, 0.15650071, 0.14615025, 0.73303093]]])

In [ ]:
array_3d[0,0,-1]

0.23127454342254583

# Convertendo para np.array




In [ ]:
lst = [1,4,7,8]
np.array(lst)


array([1, 4, 7, 8])

In [ ]:
list_of_lists = [[1,2,3],[4,5,6],[7,8,9]]
array_lst_lst = np.array(list_of_lists)
array_lst_lst

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
len(list_of_lists)

3

In [ ]:
array_lst_lst.shape

(3, 3)

In [ ]:
a = [[1,3,np.array([5,6,8])]]
a

[[1, 3, array([5, 6, 8])]]

In [ ]:
np.array((1,3,5))

array([1, 3, 5])

# Funções matemáticas

## sum

In [ ]:
a = np.random.randint(0, 10, size=(2,3))
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
a.shape

(2, 3)

In [ ]:
a.sum()

21

In [ ]:
a.sum(axis=0)

array([10,  7,  4])

In [ ]:
a.sum(axis=1)

array([16,  5])

In [ ]:
a[0].sum()

16

In [ ]:
# Sum of all elements in matrix a
# Sum of each column in matrix a (sum over rows - dimension 0)
# Sum of each row in matrix a (sum over columns - dimension 1)
# Sum of all the elements in the first LINE of matrix a

a.sum()   # soma 

a.sum(axis=0)

a.sum(axis=1)

a[:2].sum()

68

-----

## mean

In [ ]:
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
a.sum()/a.size

3.5

In [ ]:
a.mean()

3.5

In [ ]:
a.mean(axis=1)

array([5.33333333, 1.66666667])

In [ ]:
a.mean(axis=0)

array([5. , 3.5, 2. ])

In [ ]:
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
# Mean of all elements in matrix a
# Mean of each column in matrix a
# Mean of each row in matrix a
# Mean of all the elements in the first line of matrix a

np.mean(a)
# np.mean(a).round()

np.mean(a, axis=0)

a.mean(axis=1)

a[0].mean()

5.333333333333333

In [ ]:
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
a.T

array([[8, 2],
       [7, 0],
       [1, 3]])

In [ ]:
a.transpose()

array([[8, 2],
       [7, 0],
       [1, 3]])

# Operações entre np.arrays

In [ ]:
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
a.shape

(2, 3)

In [ ]:
c = np.random.randint(0,10, size=(2,3))
c

array([[2, 6, 1],
       [0, 7, 2]])

In [ ]:
a + c

array([[10, 13,  2],
       [ 2,  7,  5]])

In [ ]:
a - c

array([[ 6,  1,  0],
       [ 2, -7,  1]])

In [ ]:
x = a[0, 0] + c[-1, -1]

In [ ]:
x

10

In [ ]:
a

array([[8, 7, 1],
       [2, 0, 3]])

In [ ]:
# Shallow copy
b = a 

In [ ]:
b[0,0] = 1000

In [ ]:
b

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
a

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
# Deep copy
b = a.copy()
# b = a[:] DOESNT WORK for numpy arrays (as it worked in lists)

In [ ]:
a

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
b

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
b[0,0] = -1

In [ ]:
b

array([[-1,  7,  1],
       [ 2,  0,  3]])

In [ ]:
a

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
b = a[:]

In [ ]:
b

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
a

array([[1000,    7,    1],
       [   2,    0,    3]])

In [ ]:
b[0,0] = -1

In [ ]:
b

array([[-1,  7,  1],
       [ 2,  0,  3]])

In [ ]:
a

array([[-1,  7,  1],
       [ 2,  0,  3]])

In [ ]:
a

array([[-1,  7,  1],
       [ 2,  0,  3]])

In [ ]:
for item in a:
    for another_item in item:
        print(item, another_item)

[-1  7  1] -1
[-1  7  1] 7
[-1  7  1] 1
[2 0 3] 2
[2 0 3] 0
[2 0 3] 3


In [ ]:
a.shape

(2, 3)

In [ ]:
a

array([[-1,  7,  1],
       [ 2,  0,  3]])

In [ ]:
for i in range(2):
    for j in range(3):
        print(i, j, a[i,j])

0 0 -1
0 1 7
0 2 1
1 0 2
1 1 0
1 2 3


# Realinhando arrays

In [ ]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Concatenando

In [ ]:
# in lists: x + y

In [ ]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [ ]:
x + y

array([4, 4, 4])

In [ ]:
x.shape

(3,)